version: '3.5'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    container_name: consul-agent-1
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      - consul-net
    volumes:
      - /Users/stanley/tmp/data/consul/data/consul-agent-1:/consul/data

  consul-agent-2:
    <<: *consul-agent
    container_name: consul-agent-2
    volumes:
      - /Users/stanley/tmp/data/consul/data/consul-agent-2:/consul/data

  consul-agent-3:
    <<: *consul-agent
    container_name: consul-agent-3
    volumes:
      - /Users/stanley/tmp/data/consul/data/consul-agent-3:/consul/data

  consul-server-1: &consul-server
    <<: *consul-agent
    container_name: consul-server-1
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    volumes:
      - /Users/stanley/tmp/data/consul/data/consul-server-1:/consul/data

  consul-server-2:
    <<: *consul-server
    container_name: consul-server-2
    volumes:
      - /Users/stanley/tmp/data/consul/data/consul-server-2:/consul/data

  consul-server-bootstrap:
    <<: *consul-agent
    container_name: consul-server-0
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    volumes:
      - /Users/stanley/tmp/data/consul/data/consul-server-0:/consul/data

networks:
  consul-net:
    name: consul-net
